Recreating Frosts pull req into dev
ARandy-BADPMC/Bad-Company-Operation-Chainbreaker pull request #17
Opened 2023-05-23 15:16 UTC by ARandy-BADPMC

Various updates:

Add Frost to devs
Fix Defiance whitelist (was only added to jet whitelist, now should be in helis too)
Fix Tracked nightmare spawning (would not spawn camps if on the northern side of the map -> infinite loop)
Fix groups spawning (mechanized, tanks and infantry would not spawn in the northern side of the map -> infinite loop)
Immobilize leader in factory missions to prevent losing sight of him in the big map.

2023-05-24 17:57 UTC, KHunter-Arma commented
Wait hang on... this branch is based on main, and not dev isn't it? We have to push dev to main now before we change anything to follow what we agreed on. And this branch will have to be synced with the "new" main to make sure there are no conflicts.
@ARandy-BADPMC @frost-west

2023-05-24 18:42 UTC, frost-west commented
> the changes on dev have been merges on main it's been a while now I guess

2023-05-24 18:43 UTC, KHunter-Arma commented
Yeah Git actually says there are no changes in between and right now I'm surprised and confused again...

2023-05-25 18:22 UTC, KHunter-Arma commented
Alright, I got confused for no reason sorry... Randy did sync main with dev back in February and apparently we didn't make any commits since then. So it's all good. Just waiting for Frost to take a look at my comment in the other PR now since he said we should merge that one in first.

2023-05-31 13:57 UTC, KHunter-Arma reviewed
@frost-west can you take a look at the comment I left for the tracked nightmare spawn function and see if you need to do anything?

2023-05-31 18:25 UTC, KHunter-Arma requested changes

2023-05-31 18:25 UTC, KHunter-Arma commented on OPCB/functions/missions/gdrunken_spawn.sqf
It's good you cut down on all that stuff, but with the way it is now, it can go into an infinite loop if it can't satisfy those parameters in that area. To alleviate the same problem in the other (common) spawn function, I made it so that the max search distance gets increased if a solution isn't found. Take a look at it again if you haven't spotted that. I think something like that needs to be in here or this can get stuck. Better to have a wide-reaching task than no task right?

2023-06-01 15:24 UTC, KHunter-Arma approved these changes

2023-06-01 15:26 UTC, merged