fix developer console on editor, task spawner fix
ARandy-BADPMC/Bad-Company-Operation-Chainbreaker pull request #26
Opened 2023-06-01 08:06 UTC by JeyR01

2023-06-01 10:58 UTC, KHunter-Arma commented
I tagged you in 2 comments in the old PR I closed. We forgot some stuff...

2023-06-01 12:18 UTC, JeyR01 commented
> I tagged you in 2 comments in the old PR I closed. We forgot some stuff...

I don't see the tags :%

2023-06-01 15:55 UTC, KHunter-Arma requested changes
Nevermind the tags from the previous PR. I opened new PR with changes for that. Take a look. And take a look at any comments here and resolve the conflicts and we're good to go

2023-06-02 06:09 UTC, JeyR01 commented on OPCB/initPlayerLocal.sqf
> +if(isServer || {getPlayerUID player in _developers}) then {
that doesn't work if you want to host the mission

2023-06-02 06:12 UTC, JeyR01 commented on OPCB/initPlayerLocal.sqf
> +if(isServer || {getPlayerUID player in _developers}) then {
as in "Play in Multiplayer". Then the dev console won't show up

2023-06-02 06:16 UTC, JeyR01 commented on OPCB/initPlayerLocal.sqf
> +if(isServer || {getPlayerUID player in _developers}) then {
also it doesn't matter as I just realized it's a local variable anyway. I'll remove that

2023-06-02 08:00 UTC, KHunter-Arma commented on OPCB/initPlayerLocal.sqf
> +if(isServer || {getPlayerUID player in _developers}) then {
It should work. Have you tried it?

2023-06-02 08:10 UTC, KHunter-Arma commented on OPCB/initPlayerLocal.sqf
> +if(isServer || {getPlayerUID player in _developers}) then {
Strange... because I would have expected it to work through the second condition by actually grabbing your true UID in that case...

2023-06-02 09:53 UTC, closed without merging